services: 
  db_survey:
    image: mysql:8.0
    container_name: survey_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: survey_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  db_answer:
    image: mysql:8.0
    container_name: answer_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: answer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  survey:
    build:
      context: ./
      dockerfile: ./Survey/dockerfile
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=survey_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db_survey
      - MYSQL_PORT=3306
    depends_on:
      db_survey:
        condition: service_healthy


  answer:
    build:
      context: ./
      dockerfile: ./Answer/dockerfile
    ports:
      - "8001:8000"
    environment:
      - MYSQL_DATABASE=answer_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db_answer
      - MYSQL_PORT=3306
    depends_on:
      db_answer:
        condition: service_healthy

  reprts:
    build:
      context: ./
      dockerfile: ./Report/dockerfile
    ports:
      - "8002:8000"
    environment:
      - MYSQL_DATABASE=answer_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db_answer
      - MYSQL_PORT=3306
    depends_on:
      db_answer:
        condition: service_healthy
      answer:
        condition: service_started

  exportcsvfn:
    build:
      context: ./
      dockerfile: ./ExportCsvFn/dockerfile
    ports:
      - "8003:8000"