version: "3.9"

services: 
  db_survey:
    image: mysql:8.0
    container_name: db_survey
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: survey_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_PORT: "3306"
    ports:
      - "3308:3306"
  db_answer:
    image: mysql:8.0
    container_name: db_answer
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: answer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_PORT: "3307"
    ports:
      - "3309:3306"

  survey:
    build:
      context: ./Survey
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=Encuestas
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Server1234
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
    depends_on:
      - db_survey

  answer:
    build:
      context: ./Answer
      dockerfile: dockerfile
    ports:
      - "8001:8000"
    environment:
      - MYSQL_DATABASE=Respuestas
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Server1234
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
    depends_on:
      - db_answer

  reprts:
    build:
      context: ./Report
      dockerfile: dockerfile
    ports:
      - "8002:8000"
    depends_on:
      - db_answer
    environment:
      - MYSQL_DATABASE=Respuestas
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Server1234
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3307
    
  exportcsvfn:
    build:
      context: ./ExportCsvFn
      dockerfile: dockerfile
    ports:
      - "8003:8000"

