FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    pkg-config \
    build-essential \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copiar requirements del proyecto principal
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copiar archivos necesarios del proyecto Django
COPY ./manage.py ./
COPY ./Encuestas2/ ./Encuestas2/

# Copiar solo el microservicio Survey
COPY ./Survey/ ./Survey/

# Exponer puerto
EXPOSE 8000

# Comando para ejecutar migraciones y luego el servidor
CMD ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]
