# Generated by Django 5.2.4 on 2025-07-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_question", models.IntegerField()),
                ("id_option", models.IntegerField(null=True)),
                ("answer", models.TextField()),
            ],
        ),
    ]
