# Generated by Django 5.2.4 on 2025-07-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Answer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.TextField(null=True),
        ),
    ]
