FROM python:3.11-slim

RUN apt-get update

RUN apt-get install -y bash jq pkg-config build-essential default-libmysqlclient-dev

RUN pip install csvkit

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Exponer puerto
EXPOSE 8000

# Comando para ejecutar migraciones y luego el servidor
CMD ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]
